# Generated by Django 5.2.7 on 2025-12-08 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='subtitle',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='quotes',
            name='subtitle',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
