# Generated by Django 5.2.7 on 2025-12-08 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_books_subtitle_alter_quotes_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='subtitle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='quotes',
            name='subtitle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
